### ISSUE TITLE
Add library to JCenter or Maven

### ISSUE THREAD

**Issue by christophehenry** [zienit/try-monad-kotlin#2]
This library is not available in JCenter or Maven repos. I'd like to use it in an Android application.

**Comment by mboogerd** [comment]
Make that two requests. I would have liked to include this as well. There is no good substitute for this functionality right now:

- `Try` is being deprecated in arrow-kt because that aims to promote lazy evaluation
- Kotlin's `Result` is somewhat overlapping, but not fully so. No `flatMap` for example (and currently not even usable as a return type)
- This [Result](https://github.com/kittinunf/Result) library exposes exception type as a second type parameter, which complicates composability.

As far as I can see, this library is the most robust implementation of `Try` for Kotlin at this moment.
